CREATE TABLE users (
   id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   first_name VARCHAR ( 255 ),
   last_name VARCHAR ( 255 ),
   email VARCHAR(255) NOT NULL,
   password VARCHAR ( 255 ) NOT NULL,
   is_member BOOLEAN DEFAULT FALSE,
   is_admin BOOLEAN DEFAULT FALSE
);

CREATE TABLE messages (
   id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   title VARCHAR ( 255 ),
   timestamp TIMESTAMP WITHOUT TIME ZONE,
   text VARCHAR ( 255 ),
   user_id INTEGER
);

CREATE TABLE sessions (
  sid VARCHAR(255) NOT NULL PRIMARY KEY,
  sess JSONB NOT NULL,
  expire TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);